# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alberto's log
email: alberto.bravi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, I’m Alberto. I’m a web developer living in Rome, Italy. I am a fan of web development, programming, and technology.
  I’m also interested in innovation and i love Open Source.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://albertobravi.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: albertobravi
github_username:  albertobravi
linkedin_username:  albertobravi

google_analytics: UA-38774212-1

github_repositories:
  - tropo-webapi-php-oop
  - laravel-crud-elasticsearch
  - symfony-crud-elasticsearch

# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
